#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("AgileKonferencja.Resource", IsApplication=true)]

namespace AgileKonferencja
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int agenda = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int agenda_lista = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int AgileBrains = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int agileit = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int human = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int Icon = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int infoshare = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int Kainos = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int logo = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int travactory = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int wygramy = 2130837514;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070006
			public const int ButtonConnect = 2131165190;
			
			// aapt resource value: 0x7f070004
			public const int ImageViewLogo = 2131165188;
			
			// aapt resource value: 0x7f070009
			public const int ImageViewPrelegenci = 2131165193;
			
			// aapt resource value: 0x7f070002
			public const int LinearLayoutMain = 2131165186;
			
			// aapt resource value: 0x7f070005
			public const int TextViewMain = 2131165189;
			
			// aapt resource value: 0x7f07000a
			public const int TextViewNazwa = 2131165194;
			
			// aapt resource value: 0x7f070007
			public const int TextViewOrganizator = 2131165191;
			
			// aapt resource value: 0x7f07000b
			public const int TextViewPrelegenci = 2131165195;
			
			// aapt resource value: 0x7f070000
			public const int ToolbarAgenda = 2131165184;
			
			// aapt resource value: 0x7f070003
			public const int ToolbarMain = 2131165187;
			
			// aapt resource value: 0x7f070008
			public const int ToolbarPrelegenci = 2131165192;
			
			// aapt resource value: 0x7f070001
			public const int imageView1 = 2131165185;
			
			// aapt resource value: 0x7f07000c
			public const int menu_agenda = 2131165196;
			
			// aapt resource value: 0x7f07000e
			public const int menu_exit = 2131165198;
			
			// aapt resource value: 0x7f07000d
			public const int menu_prelegenci = 2131165197;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Agenda = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Prelegenci = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f060000
			public const int menu_bottom = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int menu_main = 2131099649;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int ApplicationName = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int OpisKonferencji = 2130968577;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int MyTheme = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
